import React from 'react'
import BasicIntro from '../Reusable/BasicIntro'
import IntroductionPage from '../Introductionpage'

const Introduction = () => {
    const introData = {
        headerdata:{
          ne: "टंकप्रसाद आचार्य (१९१२ - १९९२)",
            en: "Tanka Prasad Acharya (1912 - 1992)"
        },
        information:{ne: [
                "नेपालमा राजनीतिक परिवर्तनद्वारा नागरिक सम्मान र मानव अधिकार, सामाजिक न्याय एवं प्रजातन्त्र तथा लोक कल्याणकारी राज्यको स्थापना गरी देशको राष्ट्रिय स्वाधीनताको मार्गलाई विकसित गरी सर्वतोमुखी विकास गर्ने हेतुले शताब्दी लामो जहानिया राणा शासनलाई जन संघर्षबाट अन्त्य गर्दै बहुदलीय प्रजातान्त्रिक व्यवस्थाको स्थापना गर्न संगठित जनप्रयासतर्फ नेपालमा क्रान्तिको पहिलो सार्वजनिक विगुल फुक्ने राष्ट्रिय नेता स्वर्गीय टंकप्रसाद आचार्यले जिउज्यानको बाजी लगाई सम्वर्धन गरेको जनकल्याणकारी प्रजातन्त्र र राष्ट्रिय स्वाभिमानका मूल्य र मान्यताहरूको प्रवद्र्धन गर्नका साथै श्री आचार्यको सम्मान गर्दै उहाँको कीर्ति तथा पावन स्मृतिलाई चिरस्थायी राख्ने उद्देश्य लिएर २०५० साल वैशाख ११ गते सार्वजनिक क्षेत्रमा टंकप्रसाद आचार्य स्मृति प्रतिष्ठानको स्थापना गरिएको हो । जिल्ला प्रशासन कार्यालय काठमाडौंमा २०५० वैशाख ११ गते दर्ता गरिएको छ । साथै मिति २०६१ कार्तिक ३० मा आवद्धता नं. १६९९३ वाट प्रतिष्ठान समाज कल्याण परिषद्मा समेत आवद्ध भएको छ ।", 
                "नेपालमा राजनीतिक परिवर्तनद्वारा नागरिक सम्मान र मानव अधिकार, सामाजिक न्याय एवं प्रजातन्त्र तथा लोक कल्याणकारी राज्यको स्थापना गरी देशको राष्ट्रिय स्वाधीनताको मार्गलाई विकसित गरी सर्वतोमुखी विकास गर्ने हेतुले शताब्दी लामो जहानिया राणा शासनलाई जन संघर्षबाट अन्त्य गर्दै बहुदलीय प्रजातान्त्रिक व्यवस्थाको स्थापना गर्न संगठित जनप्रयासतर्फ नेपालमा क्रान्तिको पहिलो सार्वजनिक विगुल फुक्ने राष्ट्रिय नेता स्वर्गीय टंकप्रसाद आचार्यले जिउज्यानको बाजी लगाई सम्वर्धन गरेको जनकल्याणकारी प्रजातन्त्र र राष्ट्रिय स्वाभिमानका मूल्य र मान्यताहरूको प्रवद्र्धन गर्नका साथै श्री आचार्यको सम्मान गर्दै उहाँको कीर्ति तथा पावन स्मृतिलाई चिरस्थायी राख्ने उद्देश्य लिएर २०५० साल वैशाख ११ गते सार्वजनिक क्षेत्रमा टंकप्रसाद आचार्य स्मृति प्रतिष्ठानको स्थापना गरिएको हो । जिल्ला प्रशासन कार्यालय काठमाडौंमा २०५० वैशाख ११ गते दर्ता गरिएको छ । साथै मिति २०६१ कार्तिक ३० मा आवद्धता नं. १६९९३ वाट प्रतिष्ठान समाज कल्याण परिषद्मा समेत आवद्ध भएको छ ।", 
                "नेपालमा राजनीतिक परिवर्तनद्वारा नागरिक सम्मान र मानव अधिकार, सामाजिक न्याय एवं प्रजातन्त्र तथा लोक कल्याणकारी राज्यको स्थापना गरी देशको राष्ट्रिय स्वाधीनताको मार्गलाई विकसित गरी सर्वतोमुखी विकास गर्ने हेतुले शताब्दी लामो जहानिया राणा शासनलाई जन संघर्षबाट अन्त्य गर्दै बहुदलीय प्रजातान्त्रिक व्यवस्थाको स्थापना गर्न संगठित जनप्रयासतर्फ नेपालमा क्रान्तिको पहिलो सार्वजनिक विगुल फुक्ने राष्ट्रिय नेता स्वर्गीय टंकप्रसाद आचार्यले जिउज्यानको बाजी लगाई सम्वर्धन गरेको जनकल्याणकारी प्रजातन्त्र र राष्ट्रिय स्वाभिमानका मूल्य र मान्यताहरूको प्रवद्र्धन गर्नका साथै श्री आचार्यको सम्मान गर्दै उहाँको कीर्ति तथा पावन स्मृतिलाई चिरस्थायी राख्ने उद्देश्य लिएर २०५० साल वैशाख ११ गते सार्वजनिक क्षेत्रमा टंकप्रसाद आचार्य स्मृति प्रतिष्ठानको स्थापना गरिएको हो । जिल्ला प्रशासन कार्यालय काठमाडौंमा २०५० वैशाख ११ गते दर्ता गरिएको छ । साथै मिति २०६१ कार्तिक ३० मा आवद्धता नं. १६९९३ वाट प्रतिष्ठान समाज कल्याण परिषद्मा समेत आवद्ध भएको छ ।"
            ],
            en: [
                "With the aim of establishing a welfare-oriented state by achieving civic dignity and human rights, social justice, democracy, and public welfare through political change in Nepal, and by advancing the path of national independence and ensuring all-round development of the country, the late national leader Tank Prasad Acharya—who sounded the first public call of revolution in Nepal by organizing popular efforts to end the century-long autocratic Rana regime through mass struggle and to establish a multi-party democratic system—risked his life to promote the values and principles of people-oriented democracy and national self-respect.In order to promote these values, to honor Mr. Acharya, and to preserve his legacy and sacred memory permanently, the Tank Prasad Acharya Memorial Foundation was established in the public domain on Baisakh 11, 2050 B.S. (1993 A.D.). The foundation was registered at the District Administration Office, Kathmandu, on the same date. Furthermore, on Kartik 30, 2061 B.S. (2004 A.D.), the foundation was also affiliated with the Social Welfare Council under affiliation number 16993.",
                "With the objective of establishing civic dignity and human rights, social justice, democracy, and a welfare-oriented state through political transformation in Nepal, and of advancing national independence and ensuring the country’s overall development, the late national leader Tank Prasad Acharya—who issued the first public call for revolution in Nepal by organizing popular movements to end the century-long autocratic Rana regime and establish a multi-party democratic system—risked his life to uphold and promote the values and principles of people-centered democracy and national self-respect.In order to promote these ideals, honor Mr. Acharya, and preserve his legacy and sacred memory permanently, the Tank Prasad Acharya Memorial Foundation was established in the public sphere on Baisakh 11, 2050 B.S. (1993 A.D.). The Foundation was registered with the District Administration Office, Kathmandu, on the same date. Furthermore, on Kartik 30, 2061 B.S. (2004 A.D.), the Foundation was also affiliated with the Social Welfare Council under affiliation number 16993.",
                "With the aim of establishing civic dignity and human rights, social justice, democracy, and a welfare-oriented state through political transformation in Nepal, and of advancing the path of national independence and ensuring all-round development of the country, the late national leader Tank Prasad Acharya—who issued the first public call for revolution in Nepal by organizing mass movements to end the century-long autocratic Rana regime and establish a multi-party democratic system—risked his life to uphold and promote the values and principles of people-oriented democracy and national self-respect.To promote these values, honor Mr. Acharya, and preserve his legacy and sacred memory permanently, the Tank Prasad Acharya Memorial Foundation was established in the public domain on Baisakh 11, 2050 B.S. (1993 A.D.). The Foundation was registered with the District Administration Office, Kathmandu, on the same date. Furthermore, on Kartik 30, 2061 B.S. (2004 A.D.), the Foundation was affiliated with the Social Welfare Council under affiliation number 16993."
            ]}
    ,
    image:"https://tp-acharya.terracecafe.com.np/upload/images/tp-acharya/1712319066tankaprasad.jpg"
    }
  return (
    <div>
      <IntroductionPage data={introData}/>
    </div>
  )
}

export default Introduction
